"""adiciona campo eh_fiado ao indice de xmls

Revision ID: 27c25e58cd8e
Revises: f499d70d38e9
Create Date: 2026-08-18 15:55:55.053509
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27c25e58cd8e'
down_revision: Union[str, None] = 'f499d70d38e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_indexados', sa.Column('forma_pagamento', sa.String(length=2), nullable=True))
    # server_default garante que linhas já existentes recebam False em vez
    # de travar a migração (NOT NULL sem default falha se a tabela não
    # estiver vazia) — a lógica antiga (eh_venda_a_prazo) não identificava
    # fiado corretamente mesmo, então False é o valor seguro até a próxima
    # varredura reprocessar cada arquivo com a lógica nova.
    op.add_column(
        'xml_indexados',
        sa.Column('eh_fiado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.drop_index(op.f('ix_xml_indexados_eh_venda_a_prazo'), table_name='xml_indexados')
    op.create_index(op.f('ix_xml_indexados_eh_fiado'), 'xml_indexados', ['eh_fiado'], unique=False)
    # ### end Alembic commands ###

    # Linhas já indexadas antes desta correção estão marcadas como
    # "resolvidas" (xml_invalido=False) com a lógica antiga, que
    # confundia venda no cartão com fiado (mesma natureza de operação
    # "Venda a prazo" nos dois casos) — sem isso, elas nunca seriam
    # reprocessadas sozinhas e ficariam com eh_fiado=False (o valor
    # padrão da coluna nova) para sempre, mesmo quando são fiado de
    # verdade. Esvaziar o índice é seguro (é só um cache de performance,
    # nunca a fonte da verdade) — a próxima varredura reconstrói tudo do
    # zero, agora com o filtro correto.
    op.execute("TRUNCATE TABLE xml_indexados")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xml_indexados_eh_fiado'), table_name='xml_indexados')
    op.create_index(op.f('ix_xml_indexados_eh_venda_a_prazo'), 'xml_indexados', ['eh_venda_a_prazo'], unique=False)
    op.drop_column('xml_indexados', 'eh_fiado')
    op.drop_column('xml_indexados', 'forma_pagamento')
    # ### end Alembic commands ###
