"""adiciona valor_fiado ao indice de xmls

Revision ID: 387e26ae3c29
Revises: 27c25e58cd8e
Create Date: 2026-09-01 19:25:12.706135
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '387e26ae3c29'
down_revision: Union[str, None] = '27c25e58cd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_indexados', sa.Column('valor_fiado', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###

    # Linhas já indexadas como fiado antes desta correção têm
    # valor_fiado=NULL (a coluna não existia) e valor_total com o valor
    # errado para notas com pagamento misto (dinheiro + fiado no mesmo
    # XML) — o valor total da nota, não só a parte marcada na conta.
    # Marca essas linhas como "não resolvidas" para que a próxima
    # varredura as reprocesse (reabre e relê só esses arquivos, não a
    # pasta inteira) e preencha valor_fiado corretamente. Seguro: o índice
    # é só um cache de performance, nunca a fonte da verdade.
    op.execute("UPDATE xml_indexados SET xml_invalido = true WHERE eh_fiado = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_indexados', 'valor_fiado')
    # ### end Alembic commands ###
