"""estrutura inicial

Revision ID: 775425f06865
Revises: 
Create Date: 2026-08-04 23:46:33.113907
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '775425f06865'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_visivel', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('nome_principal', sa.String(length=150), nullable=False),
    sa.Column('nome_principal_normalizado', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_visivel')
    )
    op.create_index('ix_clientes_nome_principal_normalizado', 'clientes', ['nome_principal_normalizado'], unique=False)
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('log_erros',
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('erro', sa.String(length=500), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'FUNCIONARIO', name='perfil_usuario'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('compradores',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_alteracoes',
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('valor_antigo', sa.String(), nullable=True),
    sa.Column('valor_novo', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomes_alternativos',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nomes_alternativos_normalizado', 'nomes_alternativos', ['nome_normalizado'], unique=False)
    op.create_table('pagamentos',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('recebido_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['recebido_por_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('numero_normalizado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telefones_normalizado', 'telefones', ['numero_normalizado'], unique=False)
    op.create_table('compras',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('comprador_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'PARCIAL', 'QUITADA', name='status_compra'), nullable=False),
    sa.Column('eh_resto', sa.Boolean(), nullable=False),
    sa.Column('compra_origem_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('origem_nfe_xml', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['compra_origem_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento_compra',
    sa.Column('pagamento_id', sa.UUID(), nullable=False),
    sa.Column('compra_id', sa.UUID(), nullable=False),
    sa.Column('valor_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento_compra')
    op.drop_table('compras')
    op.drop_index('ix_telefones_normalizado', table_name='telefones')
    op.drop_table('telefones')
    op.drop_table('pagamentos')
    op.drop_index('ix_nomes_alternativos_normalizado', table_name='nomes_alternativos')
    op.drop_table('nomes_alternativos')
    op.drop_table('historico_alteracoes')
    op.drop_table('compradores')
    op.drop_table('usuarios')
    op.drop_table('log_erros')
    op.drop_table('configuracoes')
    op.drop_index('ix_clientes_nome_principal_normalizado', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
