"""adiciona limite de fiado ao cliente

Revision ID: 94e8ed403220
Revises: 387e26ae3c29
Create Date: 2026-09-01 19:43:54.328149
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94e8ed403220'
down_revision: Union[str, None] = '387e26ae3c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('limite_fiado', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'limite_fiado')
    # ### end Alembic commands ###
