"""adiciona indice permanente de xmls

Revision ID: f499d70d38e9
Revises: 7069663d64a5
Create Date: 2026-08-17 16:09:30.812682
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f499d70d38e9'
down_revision: Union[str, None] = '7069663d64a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_indexados',
    sa.Column('caminho_arquivo', sa.String(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=100), nullable=True),
    sa.Column('eh_venda_a_prazo', sa.Boolean(), nullable=False),
    sa.Column('nome_cliente_xml', sa.String(length=150), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('xml_invalido', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caminho_arquivo')
    )
    op.create_index(op.f('ix_xml_indexados_chave'), 'xml_indexados', ['chave'], unique=False)
    op.create_index(op.f('ix_xml_indexados_eh_venda_a_prazo'), 'xml_indexados', ['eh_venda_a_prazo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xml_indexados_eh_venda_a_prazo'), table_name='xml_indexados')
    op.drop_index(op.f('ix_xml_indexados_chave'), table_name='xml_indexados')
    op.drop_table('xml_indexados')
    # ### end Alembic commands ###
